server:
  port: 18081
spring:
  application:
    name: mdy-mysql-web-parentß
  cloud:
    discovery:
      enable: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 30000
#        readTimeout: 5000